import { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer";
import { Navbar } from "../components/navbar";

const ContactUs: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto my-10 flex min-h-screen flex-col items-center justify-center border bg-green-200 p-4">
        <div className="flex">
          <div className="m-3 flex-1 rounded-lg border border-black bg-white text-center">
            <h2>Contact Information</h2>
            <p>
              Welcome to Sole-Zon-Solis Energy, we are happy to answer any
              questions you might have about our services. Please fill out the
              contact us form and we will get back to you shortly!
            </p>
            <p>Phone Number</p>
            <p>Email Address</p>
          </div>
          <div className="m-3 rounded-lg border border-black bg-white text-center">
            <h2>Contact Us Form</h2>

            <form action="" className="flex flex-col px-4">
              <input
                className="my-2 w-full rounded border"
                type="text"
                placeholder="Name"
              />
              <input
                className="my-2 w-full rounded border"
                type="email"
                placeholder="Email"
              />
              <input
                className="my-2 w-full rounded border"
                type="tel"
                placeholder="Phone Number"
              />
              <input className="w-full rounded border" type="file" />
              <input className="my-2 w-full rounded border" type="submit" />
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default ContactUs;
