import { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer";
import { Navbar } from "../components/navbar";

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto my-10 flex min-h-screen flex-col items-center justify-center border bg-green-200 p-4">
        <div className="flex">
          <div className="m-3 rounded-lg border border-black bg-white text-center">
            <h2>Login</h2>

            <form action="" className="flex flex-col px-4">
              <input
                className="my-2 w-full rounded border"
                type="text"
                placeholder="Username"
              />
              <input
                className="my-2 w-full rounded border"
                type="password"
                placeholder="Password"
              />
              <input className="my-2 w-full rounded border" type="submit" />
            </form>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Login;
