import { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer";
import { Navbar } from "../components/navbar";

const Manufacturing: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center bg-green-200 p-4 my-10 border">
        <div className="m-3  w-full rounded-lg border border-black bg-white text-center">
          <h2 className="">Manufacturing</h2>
          <p className="">
            Being part of the Vita Vehiculum family means that we support the
            manufacturing of electric vehicles (EV). Utilizing our solar
            generation, Vita Vehiculum has built a new electric vehicle
            manufacturing complex right here at Sonneberg Fields. It provides
            the capability of building EV in a plant run completely off solar!
            It is much more efficient than any of our competitors! Please reach
            out via the Contact Us page for more information regarding our EV
            manufacturing.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Manufacturing;
