import { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/footer";
import { Navbar } from "../components/navbar";

const Solar: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container mx-auto my-10 flex min-h-screen flex-col items-center justify-center border bg-green-200 p-4">
        <div className="m-3  w-full rounded-lg border border-black bg-white text-center">
          <h2 className="">Solar Generation</h2>
          <p className="px-8">
            We are proud of being the newest addition to the Vita Vehiculum
            family and support their manufacturing capabilities with over 15
            acres of solar farms throughout the country. Currently our largest
            farm, Sonneberg Fields,has capabilities of generation approximately
            14000 kW/h of electricity. Our mission has always been clean energy
            and our solar generation efforts are our star in that. Please reach
            out via the Contact Us page for more information regarding
            commercial utilization.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default Solar;
